USE [master]
GO
/****** Object:  Database [PruebaSD]    Script Date: 05/05/2022 10:15:54 p. m. ******/
CREATE DATABASE [PruebaSD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaSD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PruebaSD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaSD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PruebaSD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PruebaSD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaSD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PruebaSD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PruebaSD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PruebaSD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PruebaSD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PruebaSD] SET ARITHABORT OFF 
GO
ALTER DATABASE [PruebaSD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PruebaSD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PruebaSD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PruebaSD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PruebaSD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PruebaSD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PruebaSD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PruebaSD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PruebaSD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PruebaSD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PruebaSD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PruebaSD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PruebaSD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PruebaSD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PruebaSD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PruebaSD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PruebaSD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PruebaSD] SET RECOVERY FULL 
GO
ALTER DATABASE [PruebaSD] SET  MULTI_USER 
GO
ALTER DATABASE [PruebaSD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PruebaSD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PruebaSD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PruebaSD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PruebaSD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PruebaSD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PruebaSD', N'ON'
GO
ALTER DATABASE [PruebaSD] SET QUERY_STORE = OFF
GO
USE [PruebaSD]
GO
/****** Object:  Schema [Prueba]    Script Date: 05/05/2022 10:15:57 p. m. ******/
CREATE SCHEMA [Prueba]
GO
/****** Object:  Table [Prueba].[Usuario]    Script Date: 05/05/2022 10:15:57 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Prueba].[Usuario](
	[UsuID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NULL,
	[Apellido] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[UsuID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [Prueba].[Usuario] ON 
GO
INSERT [Prueba].[Usuario] ([UsuID], [Nombre], [Apellido]) VALUES (CAST(1 AS Numeric(18, 0)), N'Deyved', N'Franco')
GO
INSERT [Prueba].[Usuario] ([UsuID], [Nombre], [Apellido]) VALUES (CAST(2 AS Numeric(18, 0)), N'steven', N'Pinzon')
GO
INSERT [Prueba].[Usuario] ([UsuID], [Nombre], [Apellido]) VALUES (CAST(3 AS Numeric(18, 0)), N'Luz Mery', N'Franco')
GO
INSERT [Prueba].[Usuario] ([UsuID], [Nombre], [Apellido]) VALUES (CAST(4 AS Numeric(18, 0)), N'mariana', N'salazar')
GO
SET IDENTITY_INSERT [Prueba].[Usuario] OFF
GO
/****** Object:  StoredProcedure [dbo].[spConsultarPersonas]    Script Date: 05/05/2022 10:15:59 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Deyved>
-- Create date: <05/05/2022>
-- Description:	<Este procedimiento consulta personas>
-- =============================================
CREATE PROCEDURE [dbo].[spConsultarPersonas] 
	
AS
BEGIN

	


SELECT [UsuID]
      ,[Nombre]
      ,[Apellido]
  FROM [Prueba].[Usuario];



END
GO
USE [master]
GO
ALTER DATABASE [PruebaSD] SET  READ_WRITE 
GO
